version: "3.8"

services:
  mysql:
    image: mysql:8-oracle
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      retries: 5
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver_opts:
      type: tmpfs
      device: tmpfs
